### ISSUE TITLE
Does not build today - missing QLOT/UTIL package?

### ISSUE THREAD

**Issue by quicklisp** [inaimathi/cl-notebook#71]
I get this:
```
; caught ERROR:
;   READ error during COMPILE-FILE: Package QLOT/UTIL does not exist. Line: 109, Column: 41, File-Position: 4215 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/cl-notebook/ddee9b7876e1ce489b09165910c76abe2301cc7f/cl-notebook-20191121-git/src/model.lisp" {100E2AA373}>
```

Full log is here: http://report.quicklisp.org/2019-11-21/failure-report/cl-notebook.html#cl-notebook

Maybe this is due to a recent change in https://github.com/fukamachi/qlot but I don't see immediately what it might be.

**Comment by fukamachi** [comment]
I never noticed `qlot/util:with-package-functions` is refered by some libraries.
`qlot/util` has been renamed to `qlot/utils` since v0.10.0.
I don't mind to add a nickname to fix this if it's the only problem.

**Comment by quicklisp** [comment]
Unfortunately there remains a problem
```; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "INSTALL-QUICKLISP" not found in the QLOT package.
```

**Comment by quicklisp** [comment]
If this is not resolved, I will not be able to include cl-notebook in the next Quicklisp update, due sometime in December.

**Comment by linnilbobo** [comment]
I found the problem, 
it needs the old version of 0.9.16 instead of the current new version of 0.10.6
i try by this:
---
林: (push #p"/home/lin/qlot-0.9.16/" asdf:*central-registry*)

(#P"/home/lin/qlot-0.9.16/" #P"/home/lin/quicklisp/quicklisp/")
林: (ql:quickload :qlot)
To load "qlot":
  Load 1 ASDF system:
    qlot
; Loading "qlot"
[package qlot/util]...............................
[package qlot].
(:QLOT)
林: (push #p"/home/lin/cl-notebook-master/" asdf:*central-registry*)

(#P"/home/lin/cl-notebook-master/" #P"/home/lin/qlot-0.9.16/"
 #P"/home/lin/quicklisp/quicklisp/")
林: (ql:quickload :cl-notebook)
To load "cl-notebook":
  Load 1 ASDF system:
    cl-notebook
; Loading "cl-notebook"
..................................................
[package cl-notebook].....................
(:CL-NOTEBOOK)
林: 
---
This story tells me that it is inappropriate to use the beta software in important places ; (

**Comment by inaimathi** [comment]
Ok, so I'm ridiculously late to this party; how do I repro the error you got at the top? Cloning `master` out to my `local-projects` followed by a `(ql:quickload :cl-notebook) (cl-notebook:main)` works fine for me locally. What am I missing?

**Comment by linnilbobo** [comment]
I apologize for what I said a few months ago

I think that’s the problem with the plot version

Try to clone this version of plot locally to see if the problem recurs
https://github.com/fukamachi/qlot.git

**Comment by inaimathi** [comment]
It looks like it works. I did merge https://github.com/inaimathi/cl-notebook/pull/72 so this might have just fixed it outright. @quicklisp - at your convenience, could you let me know if this is resolved? If not, let me know what commands I need to run locally to attempt a repro.

**Comment by quicklisp** [comment]
Works for me, thanks!
